hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70001.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70002.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70003.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70004.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70005.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70006.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70007.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70008.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70009.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70010.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70011.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70012.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70013.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70014.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70015.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70016.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70017.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70018.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70019.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70020.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70021.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70022.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70023.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70024.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70025.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70026.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70027.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70028.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70029.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70030.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70031.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70032.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70033.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70034.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70035.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70036.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70037.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70038.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70039.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70040.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70001.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70002.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70003.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70004.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70005.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70006.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70007.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70008.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70009.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70010.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70011.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70012.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70013.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70014.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70015.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70016.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70017.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70018.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70019.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70020.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70021.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70022.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70023.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70024.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70025.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70026.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70027.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70028.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70029.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70030.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70031.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70032.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70033.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70034.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70035.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70036.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70037.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70038.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70039.sh
hep_sub /afs/ihep.ac.cn/users/l/luoxj/Deconvolution_Sim/auto_calib_decon_toolkit/get_averageWaveform/run-step1/run_step1_70040.sh
